language: go
go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - master

cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod

git:
 depth: 10

matrix:
 fast_finish: true
 allow_failures:
   - go: master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - llvm-3.9
      - clang-3.9
      - libclang1-3.9
      - libclang-3.9-dev

env:
  global:
    - CC=clang CXX=clang++

install:
  - mkdir -p /home/travis/bin
  - sudo ln -s /usr/bin/clang-3.9 /home/travis/bin/clang
  - sudo ln -s /usr/bin/llvm-config-3.9 /home/travis/bin/llvm-config
  - sudo ldconfig

  - llvm-config --version
  - llvm-config --includedir
  - llvm-config --libdir
  - clang --version

  - make install-dependencies
  - make install-tools

script:
  # Install the project
  - make install

  # Test without any coverage
  - make test-full
